### ISSUE TITLE
getSkuDetails() failed for queryProductDetailsAsync. Response code: 3

### ISSUE THREAD

**Issue by giantss** [dooboolab-community/flutter_inapp_purchase#472]
An exception occurs when calling getProducts on the Android platform (see Actual behavior for details). I checked the environment Google Play Store is logged in.

### Version of flutter_inapp_purchase
flutter_inapp_purchase: ^5.4.2

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

await FlutterInappPurchase.instance.getProducts(productLists);

No exception occurs

### Actual behavior

```
W/BillingClient(22544): getSkuDetails() failed for queryProductDetailsAsync. Response code: 3
E/DoobooUtils(22544): Error Code : 3
E/flutter (22544): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(getProducts, E_SERVICE_ERROR, Billing is unavailable. This may be a problem with your device, or the Play Store may be down., null)
E/flutter (22544): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (22544): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (22544): <asynchronous suspension>
E/flutter (22544): #2      FlutterInappPurchase.getProducts (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:152:24)
E/flutter (22544): <asynchronous suspension>
E/flutter (22544): #3      MyPayController.getProduct (package:tk_hsk/app/modules/pay/controllers/pay_controller.dart:137:14)
E/flutter (22544): <asynchronous suspension>
E/flutter (22544): #4      MyPayController.onInit (package:tk_hsk/app/modules/pay/controllers/pay_controller.dart:106:5)
E/flutter (22544): <asynchronous suspension>
```

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior

await FlutterInappPurchase.instance.getProducts(productLists);

**Comment by giantss** [comment]
s this plugin no longer maintained?
